# Generated by Django 5.2.8 on 2025-11-09 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id_ach', models.AutoField(primary_key=True, serialize=False)),
                ('tip', models.CharField(max_length=50)),
                ('nazv', models.TextField()),
                ('achiv_b', models.IntegerField()),
            ],
            options={
                'db_table': 'achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id_abit', models.AutoField(primary_key=True, serialize=False)),
                ('fam', models.CharField(max_length=50)),
                ('imya', models.CharField(max_length=50)),
                ('otch', models.CharField(blank=True, max_length=50, null=True)),
                ('pol', models.CharField(max_length=1)),
                ('dr', models.DateField()),
                ('mr', models.TextField()),
                ('adr', models.TextField()),
                ('tel', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('snils', models.CharField(max_length=14)),
                ('pasp_ser', models.CharField(max_length=10)),
                ('pasp_num', models.CharField(max_length=10)),
                ('pasp_kem', models.TextField()),
                ('pasp_data', models.DateField()),
                ('pasp_code', models.CharField(max_length=10)),
                ('prev_level', models.CharField(max_length=20)),
                ('sred_bal', models.FloatField()),
                ('obshag', models.BooleanField()),
                ('needs_spec', models.BooleanField()),
            ],
            options={
                'db_table': 'applicants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApplicantAchievement',
            fields=[
                ('id_ach_ab', models.AutoField(primary_key=True, serialize=False)),
                ('podtvr', models.BooleanField(default=False)),
                ('fail', models.TextField()),
                ('dobav', models.DateTimeField()),
                ('god', models.IntegerField()),
            ],
            options={
                'db_table': 'applicant_achievements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id_aplic', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('reg_num', models.CharField(max_length=20)),
                ('forma', models.CharField(max_length=10)),
                ('fin', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'applications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lgot',
            fields=[
                ('id_lgot', models.AutoField(primary_key=True, serialize=False)),
                ('opisan_lg', models.TextField()),
            ],
            options={
                'db_table': 'lgot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id_prog', models.AutoField(primary_key=True, serialize=False)),
                ('kod', models.CharField(max_length=20)),
                ('nazv', models.TextField()),
                ('srok', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'programs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecUslov',
            fields=[
                ('id_spec_uslov', models.AutoField(primary_key=True, serialize=False)),
                ('opisan', models.TextField()),
            ],
            options={
                'db_table': 'spec_uslov',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StrokiZayav',
            fields=[
                ('stroki_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('priorit', models.SmallIntegerField()),
            ],
            options={
                'db_table': 'stroki_zayav',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipObraz',
            fields=[
                ('id_tip_obraz', models.AutoField(primary_key=True, serialize=False)),
                ('tip_obr', models.BooleanField()),
            ],
            options={
                'db_table': 'tip_obraz',
                'managed': False,
            },
        ),
    ]
