# Generated by Django 5.2.8 on 2025-11-09 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='achievement',
            table='public.achievements',
        ),
        migrations.AlterModelTable(
            name='applicant',
            table='public.applicants',
        ),
        migrations.AlterModelTable(
            name='applicantachievement',
            table='public.applicant_achievements',
        ),
        migrations.AlterModelTable(
            name='application',
            table='public.applications',
        ),
        migrations.AlterModelTable(
            name='lgot',
            table='public.lgot',
        ),
        migrations.AlterModelTable(
            name='program',
            table='public.programs',
        ),
        migrations.AlterModelTable(
            name='specuslov',
            table='public.spec_uslov',
        ),
        migrations.AlterModelTable(
            name='strokizayav',
            table='public.stroki_zayav',
        ),
        migrations.AlterModelTable(
            name='tipobraz',
            table='public.tip_obraz',
        ),
    ]
