# Generated by Django 5.2.8 on 2025-11-09 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_alter_achievement_table_alter_applicant_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='achievement',
            table='achievements',
        ),
        migrations.AlterModelTable(
            name='applicant',
            table='applicants',
        ),
        migrations.AlterModelTable(
            name='applicantachievement',
            table='applicant_achievements',
        ),
        migrations.AlterModelTable(
            name='application',
            table='applications',
        ),
        migrations.AlterModelTable(
            name='lgot',
            table='lgot',
        ),
        migrations.AlterModelTable(
            name='program',
            table='programs',
        ),
        migrations.AlterModelTable(
            name='specuslov',
            table='spec_uslov',
        ),
        migrations.AlterModelTable(
            name='strokizayav',
            table='stroki_zayav',
        ),
        migrations.AlterModelTable(
            name='tipobraz',
            table='tip_obraz',
        ),
    ]
