# Generated by Django 5.2.8 on 2025-11-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_alter_achievement_table_alter_applicant_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lgot',
            table='Lgot',
        ),
        migrations.AlterModelTable(
            name='tipobraz',
            table='Tip_obraz',
        ),
    ]
