# Generated by Django 5.2.8 on 2025-11-11 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_lgot_table_alter_tipobraz_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('main', 'Обязательный'), ('quota', 'Квота'), ('achievement', 'Достижение'), ('other', 'Дополнительный')], max_length=20)),
                ('file', models.FileField(upload_to='docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтвержден'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.applicant')),
            ],
            options={
                'db_table': 'uploaded_documents',
                'managed': True,
            },
        ),
    ]
