# Generated by Django 5.2.8 on 2025-11-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0005_uploadeddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='reason',
            field=models.TextField(blank=True),
        ),
    ]
