# Generated by Django 5.2.8 on 2025-11-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0006_uploadeddocument_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lgot',
        ),
        migrations.DeleteModel(
            name='SpecUslov',
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('snils', 'СНИЛС'), ('education', 'Документ об образовании'), ('quota', 'Документ для квоты'), ('achievement', 'Документ о достижениях')], max_length=20),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='status',
            field=models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Подтверждён'), ('rejected', 'Отклонён')], default='pending', max_length=20),
        ),
    ]
