# Generated by Django 5.2.8 on 2025-11-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_delete_lgot_delete_specuslov_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lgot',
            fields=[
                ('id_lgot', models.AutoField(primary_key=True, serialize=False)),
                ('Opisan_lg', models.TextField()),
            ],
            options={
                'db_table': 'Lgot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecUslov',
            fields=[
                ('id_spec_uslov', models.AutoField(primary_key=True, serialize=False)),
                ('opisan', models.TextField()),
            ],
            options={
                'db_table': 'spec_uslov',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='doc_type',
            field=models.CharField(choices=[('passport', 'Паспорт'), ('snils', 'СНИЛС'), ('education', 'Документ об образовании'), ('quota', 'Квота'), ('achievement', 'Достижение')], max_length=20),
        ),
    ]
