# Generated by Django 5.2.8 on 2025-11-17 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_lgot_specuslov_alter_uploadeddocument_doc_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новая (ещё не выгружена в файл)'), ('sent', 'Файл отправлен в ФИСГИА'), ('accepted', 'Принято ФИСГИА'), ('rejected', 'Отклонено ФИСГИА')], default='new', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('application', models.ForeignKey(db_column='id_aplic', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='fisgia_requests', to='admissions.application')),
            ],
            options={
                'db_table': 'application_requests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'Новая (ещё не выгружена в файл)'), ('sent', 'Файл отправлен в ФИСГИА'), ('accepted', 'Подтверждено ФИСГИА'), ('rejected', 'Отклонено ФИСГИА')], default='new', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admissions.applicant')),
            ],
            options={
                'db_table': 'verification_requests',
                'managed': True,
            },
        ),
    ]
