# Generated by Django 5.2.8 on 2025-11-17 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_applicationrequest_verificationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationrequest',
            name='application',
            field=models.ForeignKey(db_column='id_aplic', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='fisgia_requests', to='admissions.application'),
        ),
    ]
