# Generated by Django 5.2.8 on 2025-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0010_alter_applicationrequest_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая (ещё не выгружена)'), ('sent', 'Отправлена в ФИСГИА'), ('accepted', 'ФИСГИА подтвердила'), ('rejected', 'ФИСГИА отклонила')], default='new', max_length=20),
        ),
    ]
